### ISSUE TITLE
Bugs with "Progressively enhanced form that can add or remove inputs"

### ISSUE THREAD

**Issue by rogueyoshi** [theetrain/this-week-in-svelte#1]
Nice demo, I could see myself using an approach like this. I didn't catch when you went over these in the stream, but I found a couple bugs/caveats.

1. Prior inputs will get randomly cleared when adding new ones (but NOT if JS is disabled).
2. Adding inputs creates new browser history elements.

**Comment by theetrain** [comment]
Thanks for the report, I decided to fix this by using JS client-side if present. Otherwise, it'll fall back to the online form.

I couldn't solve the problem with `form` containing new items; the input value wouldn't update predictably.
